### ISSUE TITLE
JS not loading on page change

### ISSUE THREAD

**Issue by cmike444** [drodrigues/material-design-rails#1]
I am using your gem and have followed the steps in your documentation, however I am having issues loading the javascript on a page change. It seems to only work on a hard refresh.

Do you have an idea on how to fix this?

**Comment by jerson00** [comment]
I have the same problem!

**Comment by drodrigues** [comment]
Hello,

This problem occur because you have the turbolinks activated. The google's material apply your components on page load.

You can try solve this using the turbolinks's methods + Google Material method to update registered components in the current DOM.

Ex:

``` javascript
$(document).on('ready page:load', function(event) {
  componentHandler.upgradeAllRegistered();
});
```

Thanks
